### PR TITLE
Handle API calls errors - closes #14

### LINKED ISSUE #14: Alert API calls errors
Add .catch block to axios call i alert error instead of console.logging. To the existing .catch blocks (verifyTx call and isWeb3Connected call) add alert instead of console logging message.
Purpose of this is not to create handle errors mechanism thus this is just small demo app (so we don't need complete log, just UI indicator to end-user that something went wrong).

### PR DESCRIPTION
**Pull request by andrejrakic**
Added also abilty to call onCompute function when Users clicks Enter on keyboard

### CODE REVIEW

File: client/src/components/Prove/Prove.js [hunk 1]
```diff
@@ -64,6 +65,10 @@ export default function Prove() {
 		compute();
 	};
 
+	let onPressEnter = (event) => {
+		if (event.key === 'Enter') onCompute();
+	};
+
```
Comment (andrejrakic) [inline client/src/components/Prove/Prove.js:71]: This is good addition ;)

**Review by andrejrakic — COMMENTED** [review]
Aprrove, looks fine!
